-- Service Types
INSERT INTO SERVICE_TYPES (SERVICE_TYPE_ID, SERVICE_NAME, DESCRIPTION)
VALUES (1, 'Oil Change', 'Engine oil replacement');
INSERT INTO SERVICE_TYPES (SERVICE_TYPE_ID, SERVICE_NAME, DESCRIPTION)
VALUES (2, 'Tire Rotation', 'Rotation of tires for even wear');
INSERT INTO SERVICE_TYPES (SERVICE_TYPE_ID, SERVICE_NAME, DESCRIPTION)
VALUES (3, 'Brake Inspection', 'Check and replace brake pads if needed');
INSERT INTO SERVICE_TYPES (SERVICE_TYPE_ID, SERVICE_NAME, DESCRIPTION)
VALUES (4, 'Battery Replacement', 'Install new vehicle battery');
INSERT INTO SERVICE_TYPES (SERVICE_TYPE_ID, SERVICE_NAME, DESCRIPTION)
VALUES (5, 'Full Service', 'Complete inspection and tune-up');

-- Vehicles
INSERT INTO VEHICLES (OWNER_NAME, VEHICLE_MODEL, LICENSE_PLATE, SERVICE_DATE, SERVICE_COST, SERVICE_TYPE_ID)
VALUES ('Alice Brown', 'Honda Civic', 'ABC123', '2024-06-10', 120.00, 1);
INSERT INTO VEHICLES (OWNER_NAME, VEHICLE_MODEL, LICENSE_PLATE, SERVICE_DATE, SERVICE_COST, SERVICE_TYPE_ID)
VALUES ('John Miller', 'Toyota Corolla', 'XYZ789', '2024-07-15', 200.50, 5);