CREATE TABLE SERVICE_TYPES (
	SERVICE_TYPE_ID NUMERIC(4,0) PRIMARY KEY,
	SERVICE_NAME VARCHAR(50) NOT NULL,
	DESCRIPTION VARCHAR(100)
);

CREATE TABLE VEHICLES (
	VEHICLE_ID NUMERIC(6,0) PRIMARY KEY AUTO_INCREMENT,
	OWNER_NAME VARCHAR(50) NOT NULL,
	VEHICLE_MODEL VARCHAR(50) NOT NULL,
	LICENSE_PLATE VARCHAR(15) UNIQUE NOT NULL,
	SERVICE_DATE DATE NOT NULL,
	SERVICE_COST NUMERIC(8,2),
	SERVICE_TYPE_ID NUMERIC(4,0),
	FOREIGN KEY (SERVICE_TYPE_ID) REFERENCES SERVICE_TYPES(SERVICE_TYPE_ID)
);

CREATE TABLE sec_user (
  userId            BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  email             VARCHAR(75) NOT NULL UNIQUE,
  encryptedPassword VARCHAR(128) NOT NULL,
  enabled           BIT NOT NULL 
);

CREATE TABLE sec_role(
  roleId   BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  roleName VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE user_role
(
  id     BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  userId BIGINT NOT NULL,
  roleId BIGINT NOT NULL
);

ALTER TABLE user_role
  ADD CONSTRAINT user_role_fk1 UNIQUE (userId, roleId);

ALTER TABLE user_role
  ADD CONSTRAINT user_role_fk2 FOREIGN KEY (userId)
  REFERENCES sec_user (userId);
 
ALTER TABLE user_role
  ADD CONSTRAINT user_role_fk3 FOREIGN KEY (roleId)
  REFERENCES sec_role (roleId);