CREATE TABLE SERVICE_TYPES (
SERVICE_TYPE_ID NUMERIC(4,0) PRIMARY KEY,
SERVICE_NAME VARCHAR(50) NOT NULL,
DESCRIPTION VARCHAR(100)
);

CREATE TABLE VEHICLES (
VEHICLE_ID NUMERIC(6,0) PRIMARY KEY AUTO_INCREMENT,
OWNER_NAME VARCHAR(50) NOT NULL,
VEHICLE_MODEL VARCHAR(50) NOT NULL,
LICENSE_PLATE VARCHAR(15) UNIQUE NOT NULL,
SERVICE_DATE DATE NOT NULL,
SERVICE_COST NUMERIC(8,2),
SERVICE_TYPE_ID NUMERIC(4,0),
FOREIGN KEY (SERVICE_TYPE_ID) REFERENCES SERVICE_TYPES(SERVICE_TYPE_ID)
);